default[:loggly][:application]        = 'loggly'
default[:loggly][:destination_host]   = 'logs.loggly.com'
default[:loggly][:domain]             = 'updateme'
default[:loggly][:password]           = 'updateme'
default[:loggly][:username]           = 'updateme'
default[:loggly][:syslog_protocol]    = 'tcp'
