default[:loggly][:domain] = "updateme"
default[:loggly][:syslog_protocol] = "tcp"
default[:loggly][:application] = "loggly"
default[:loggly][:username] = "updateme"
default[:loggly][:password] = "updateme"
