#!/bin/bash

# Source my jenkins config if available
if [ -f ~/.jenkins.sh ]; then
  . ~/.jenkins.sh
fi

# Exit with error if any command returns non zero
set -e

# Chef expects the cookbooks in cookbooks directory
mkdir cookbooks
for f in $(ls -a |egrep -v '^cookbooks$' |egrep -v '^\.$|^\.\.$|^\.git$'); do
  /bin/mv $f cookbooks
done
echo "GIT_SHA=$GIT_COMMIT" > ./cookbooks/.build

# Build and upload artifact
# Cookbooks builds are set to public
set +e ; rvm system ; set -e
heirloom upload -n cookbooks -i $GIT_COMMIT -e .git -d . -p
