#!/bin/bash

# Set build dir to root below script dir
script_dir="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dir=`echo $script_dir | sed -e 's/\/script//'`

# Chef expects the cookbooks in cookbooks directory
cd $dir
mkdir cookbooks
/bin/mv * cookbooks
echo "GIT_SHA=$GIT_COMMIT" > ./cookbooks/.build

# Build and upload artifact
# Cookbooks builds are set to public
rvm system
/usr/bin/heirloom build -n cookbooks -i $GIT_COMMIT -d . -p
